### ISSUE TITLE
Including dice-roller.js causes app to load forever

### ISSUE THREAD

**Issue by zaweb** [GreenImp/rpg-dice-roller#37]
I'm having two issues with rpg-dice-roller. 

First, npmjs.org does not have the current release (1.5.0); it only has up to 1.3.0.

Also, including dice-roller.js causes my entire app to load forever (even if I'm not calling it dice-roller.js). The app just sits in a loading state forever. When I remove the include for dice-roller.js, the app loads fine. I've verified that this issue exists in 1.3.0 and 1.5.0. I've not tried other versions. 

I don't think it's my code because merely doing this:
`require('./dice-roller.js')`
causes my app to sit in a loading state forever. 

There are no errors being thrown. I only see these warnings, but they appear to be irrelevant:

> webpackHotDevClient.js:138 ./src/dice-roller.js
>   Line 11:   'use strict' is unnecessary inside of modules  strict
>   Line 24:   'use strict' is unnecessary inside of modules  strict
>   Line 275:  Expected a default case                        default-case
>   Line 719:  Missing radix parameter                        radix

I'm running NodeJS 8.11.2.

Thanks!

**Comment by GreenImp** [comment]
I've just fixed the last two errors ("Expected a default case default-case" and "Missing radix parameter radix"). However, you're correct, none of those should cause an issue like you're seeing.

I have just updated NPM with the latest version. Thanks for pointing that out!

I'll look into the infinite load issue. Are you able to give me any examples of your code that uses it? Do you see it when the dice roller is the only required script, or does it only happen if there are other required scripts?

**Comment by zaweb** [comment]
Thank you for your speedy response!

My app has numerous scripts that are required:
```
import { configure, observable, action, toJS } from 'mobx'
import { firebase, db } from './firebase'
import adminStore from './adminStore'
require('babel-polyfill')
require('rpg-dice-roller/dice-roller.js')
```
adminStore is my own creation. There's only one function in there, which just pulls data from Firebase.
Unfortunately, my app won't load without these required scripts so I've not tried it stand-alone. 

I'm not actually using the dice roller; I can't get that far because simply requiring it causes the app to load forever. So I don't have any examples to provide I'm afraid.

I'm can accept the possibility that the issue is something to do with my app. I just have no way to debug it because there are no errors in the console.

**Comment by zaweb** [comment]
Oh, and I should probably point out that this is a ReactJS app, and I'm using reactstrap as well.

**Comment by GreenImp** [comment]
Thanks for the info. I've realised that there was a fundamental bug in how the dice roller was being included in NPM scripts.. in that it wasn't.

I'd somehow not include a `main` property in the `package.json` file, meaning that scripts didn't know what to load. I've fixed that, and pushed up hotfix 1.5.1.
I've also tested it on npm runkit, and it is loading okay: https://runkit.com/embed/kylfzglf15hn

Could you let me know if that fixes your issue?

**Comment by zaweb** [comment]
Hmmm... Unfortunately, the issue remains. I updated to 1.5.1, but I'm still experiencing the same behavior. App still loads forever... :(

**Comment by GreenImp** [comment]
I've just created a test NPM project and included all of the modules you've listed above (Excluding `adminStore` obviously), and it is working no problems.

The code I have in my test script is simply:

```javascript
require('mobx');
require('firebase');
require('babel-polyfill');

// require the dice-roller library
const dr = require('rpg-dice-roller');

// create a new instance of the DiceRoller
var diceRoller  = new dr.DiceRoller();

// roll the dice
diceRoller.roll('4d20-L');

// get the latest dice rolls from the log
var latestRoll = diceRoller.getLog().shift();

// output the latest roll - it has a toString method for nice output
console.log(latestRoll + '');
```

Within a second I get the roll output to the console.

I've not use ReactJS in many years, so I'm not entirely sure how/if it differs to requiring with a pure node environment.
Are you able to get another basic react app running with those dependencies (potentially without the `react-loadable` module), or does that also get stuck? I'm just trying to ascertain if it is something specific to that app.

**Comment by zaweb** [comment]
I tried including dice-roller in my App.js. I now have a more descriptive error (I hope):

> TypeError: Cannot set property 'DiceRoller' of undefined
> (anonymous function)
> node_modules/rpg-dice-roller/dice-roller.js:1025
>   1022 |     }
>   1023 |   };
>   1024 | 
> > 1025 |   exports.DiceRoller = DiceRoller;
>   1026 |   exports.DiceRoll = DiceRoll;
>   1027 | }));
>   1028 |

**Comment by GreenImp** [comment]
Hmm seems like it can't find the `export` object.

I don't have a react setup to test with, and it's been a while since I used it, so I'm not sure of setting up a test app to debug this properly, but I'm assuming the problem is that it's falling into the AMD check (https://github.com/GreenImp/rpg-dice-roller/blob/94e532593d7424d64a80d848d405b8f0cd211240/dice-roller.js#L13), but failing to get the scope property.

I've added a change to the `https://github.com/GreenImp/rpg-dice-roller/tree/feature/37-including-dice-roller-js-causes-app-to-load-f` branch.

Are you able to give that a go and see if it fixes the issue?

**Comment by zaweb** [comment]
Hey, that worked! :-) Thanks!!!

**Comment by GreenImp** [comment]
Fab. I'll get that merged in as a hotfix.
